language: c
dist: bionic
osx_image: xcode11.2
addons:
  apt:
    packages: gcc-multilib-i686-linux-gnu gcc-multilib-s390x-linux-gnu gcc-multilib-x86-64-linux-gnu gcc-multilib-x86-64-linux-gnux32

install:
  - gem install rspec
  - gem install rubocop -v 0.57.2
script:
  - cd test && rake ci
  - make -s
  - make -s DEBUG=-m32 #32-bit architecture with 64-bit support
  - make -s DEBUG=-m32 UNITY_SUPPORT_64= #32-bit build without 64-bit types
  - make -s UNITY_INCLUDE_DOUBLE= # without double
  - cd ../extras/fixture/test && rake ci
  - make -s default noStdlibMalloc
  - make -s C89
  - cd ../../../examples/example_1 && make -s ci
  - cd ../example_2 && make -s ci
  - cd ../example_3 && rake

jobs:
 include:
    - name: Linux GCC x64
    - name: Linux GCC Arm64
      arch: arm64
    - name: macOS Clang x64
      os: osx
      before_install: rvm install 2.6 && rvm use 2.6 && ruby -v
